### PR TITLE
Netrunner search command et al

### LINKED ISSUE #84: List rendering on Netrunner cards fails
See the cards Deuces Wild and Wildcat Strike.

### PR DESCRIPTION
**Pull request by distributive**
- Adds Netrunner search command for listing all cards that match a set of criteria (based on the syntax of [NetrunnerDB](https://netrunnerdb.com/en/syntax))
- Fixes #84 

Note that the search command does not support the following queries:
- `c` - cycle
- `r` - release date
- `b` - ban list
- `z` - rotation

### CODE REVIEW

File: src/Tablebot/Plugin/Netrunner.hs [hunk 1]
```diff
@@ -60,11 +59,62 @@ fuzzyQueryCard pairs = closestValueWithCosts editCosts unpackedPairs . unpack
...
+    toEquality _ = \_ _ -> True
+    filterBool :: Char -> (Card -> Maybe Bool) -> Text -> ([Card] -> [Card])
+    filterBool ':' f _ = filter (fromMaybe False . f)
+    filterBool '!' f _ = filter (fromMaybe True . f)
+    filterBool _ _ _ = id
+
+-- | @pairsToQuery@ takes a set of search query pairs ands turns it into a link
+-- to an equivalent search on NetrunnerDB.
+pairsToQuery :: [(String, Char, String)] -> Text
+pairsToQuery pairs = "<https://netrunnerdb.com/find/?q=" <> replace " " "+" (intercalate "+" queries) <> ">"
```
Comment (finnbar) [inline src/Tablebot/Plugin/Netrunner.hs:115]: that's a very cool use of `intercalate`
although this is the source of the bug where a fuzzy search you've applied (e.g. `f:weyland`) isn't applied in the link - so the `more` link gives a bad NRDB page

File: src/Tablebot/Plugin/Netrunner/Faction.hs [hunk 2]
```diff
@@ -29,7 +30,14 @@ data Factions = Factions {content :: ![Faction]} deriving (Show, Generic)
 defaultFactions :: Factions
 defaultFactions = Factions {content = []}
 
-instance FromJSON Faction
+instance FromJSON Faction where
+  parseJSON (Object v) = do
```
Comment (L0neGamer) [inline src/Tablebot/Plugin/Netrunner/Faction.hs:34]: Use `withObject` instead of this, so there aren't holes in the function

File: src/Tablebot/Plugin/Netrunner.hs [hunk 3]
```diff
@@ -60,11 +59,62 @@ fuzzyQueryCard pairs = closestValueWithCosts editCosts unpackedPairs . unpack
...
+    filterText _ _ _ = id
+    filterInt :: Char -> (Card -> Maybe Int) -> Text -> ([Card] -> [Card])
+    filterInt sep f x = case readMaybe $ unpack x of
+      Nothing -> id
+      Just x' -> filter (\c -> (fromMaybe False) $ ((toEquality sep) x') <$> f c)
+    toEquality :: Char -> (Int -> Int -> Bool)
+    toEquality ':' = (==)
+    toEquality '!' = (/=)
+    toEquality '>' = (<) -- These are right, see the @filterInt@ for their application
+    toEquality '<' = (>)
```
Comment (L0neGamer) [inline src/Tablebot/Plugin/Netrunner.hs:105]: I think this swap is unclear - as discussed, can use infix notation to make usage clearer

**Review by finnbar — APPROVED** [review]
Astounding. You might wanna update the parser as discussed on Discord, but otherwise looks legit.

File: src/Tablebot/Plugin/Netrunner.hs (hunk 1 above)
Comment (distributive) [reply src/Tablebot/Plugin/Netrunner.hs:115]: This has now been solved, but highlights a discrepency in that my search is non-exclusive (`f:n` matches any faction name containing an `n` - which is most of them) whereas NetrunnerDB's search is exclusive (`f:n` autocompletes to `f:nbn`).

Should the search algorithm I use be made to mirror this?

Comment (distributive) [reply src/Tablebot/Plugin/Netrunner.hs:115]: As discussed, the search algorithm will be changed.
